### PR TITLE
Fix deprecations on 0.7

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by timholy** [comment]
Bump. It would be nice to get this merged and tagged, because now it's not even sufficient to work on my local branch since https://discourse.julialang.org/t/package-compatibility-caps/15301.

**Comment by timholy** [comment]
@mlewe, in case you're worried about backwards-compatibility: if you merge and tag this, people running Julia 0.6 or older will continue to receive the old version of the package, only people on Julia 0.7 and higher will get this version. (Thanks to the package system.)

So if you already have [attobot turned on](https://github.com/attobot/attobot) this is probably <20 seconds worth of work for you: click merge, click "releases" on the main page and specify a version number (it should be `v0.4.0`) as specified in the attobot documentation, and you can go back to your regularly-scheduled life.

**Comment by mlewe** [comment]
@timholy thanks a lot for your contribution.
I'm very sorry for being so unresponsive.
In case of emergency, I'm always reachable by email.

**Comment by timholy** [comment]
Thanks for merging it and making a release!

**Pull request merged**
